server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-14285938.okta.com/oauth2/default
      client:
        registration:
          user-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaaqrii9hcLWJlLH5d7
            client-secret: bj65v_7728toaSRbAZ5HM_3hvKKXsew0x8Y6lWQaEZWArXOIRcHGwFm3KXEL4-wx

        provider:
          okta:
            issuer-uri: https://dev-14285938.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        evenConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfcalls: 5
        autotmaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-14285938.okta.com/oauth2/default
    audience: api://default
